#!/usr/bin/bash

set -e

# ---------- ---------- ---------- ---------- ---------- ----------

# Get the default Asterisk + app_rpt versions from newest package version
ASL_PKG_INFO=$(apt-cache show asl3-asterisk	2>/dev/null	\
	       | grep Version					\
	       | head -1					\
	      )
ASL_PKG_INFO="${ASL_PKG_INFO#Version: *:}"
AST_PKG="${ASL_PKG_INFO%+*}"
ASL_PKG_INFO="${ASL_PKG_INFO#${AST_PKG}+asl3-}"
RPT_PKG="${ASL_PKG_INFO%-*}"
ASL_PKG_INFO="${ASL_PKG_INFO#${RPT_PKG}-}"
REL_PKG="${ASL_PKG_INFO%.deb*}"

# ---------- ---------- ---------- ---------- ---------- ----------

# Build options
BUILD_OPTIONS=(terse)

# ---------- ---------- ---------- ---------- ---------- ----------

usage()
{
    cat <<_EOT_ 1>&2
Usage : $0 [-a ASTV] [-v RPTV] [-r RELV] [-d DESTDIR] [-t] [-l] [-m MERGE_DIR] [-x] OPTIONS ACTIONS 

Options :
  -a  Asterisk version        (e.g. 22.2.0)
  -v  ASL/app_rpt version     (e.g. 3.3.0)
  -r  Release version         (e.g. 1)
  -d  Local install directory (default: "/")
  -l  Create merged source directory with symlinks
  -m  Merge directory path    (default: based on version #'s)
  -t  Setup test suite
  -x  Compare source file content vs. modification dates

OPTIONS (specify zero or more) :
  debug   - build with "debug" options
  devmode - build with "development" options
  thin    - disable most modules from building
  zap     - start with empty merged source directory

ACTIONS (specify one or more) :
  source  - create the merged source directory
  clean   - "clean" the merged source directory
  build   - "build" the source code
  install - "install" the build results, locally
  package - create Debian packages

Note: specifying the "build", "install", or "package" actions will, if needed,
      create the merged source directory.

Note: the Asterisk, ASL/app_rpt, and Release versions will default to those
      of the currently downloaded source code directories.  If the source
      directories are not yet available then the version numbers will be
      derived from the currently installed "asl3-asterisk" package.  You
      can also use the "AST_VER", "RPT_VER", and "REL_VER" environment
      variables to specify the versions.
_EOT_
    exit 1
}

# ---------- ---------- ---------- ---------- ---------- ----------

DESTDIR=${DESTDIR:-"/"}
EDITOR=${EDITOR:-${ALT_EDIT:-vim}}
export EMAIL=${EMAIL:-"builder@allstarlink.org"}
USE_COMPARE=0
USE_SYMLINKS=0
DO_TEST=0

# check if root
SUDO=""
if [ $EUID != 0 ]; then
    SUDO="sudo"
    SUDO_EUID=$(${SUDO} id -u)
    if [ ${SUDO_EUID} -ne 0 ]; then
	echo "This script must be run as root or with sudo"
	exit 1
    fi
fi

while getopts "a:d:lm:r:tv:x" o; do
    case "${o}" in
    "a" )
	AST_VER=${OPTARG}
	;;
    "d" )
	DESTDIR=${OPTARG}
	;;
    "r" )
	REL_VER=${OPTARG}
	;;
    "v" )
	RPT_VER=${OPTARG}
	;;
    "l" )
	USE_SYMLINKS=1
	;;
    "m" )
	MERGE_DIR=${OPTARG}
	;;
    "t" )
	DO_TEST=1
	;;
    "x" )
	USE_COMPARE=1
	;;
    * )
	echo "***"				1>&2
	echo "*** Unrecognized option \"${o}\""	1>&2
	echo "***"				1>&2
	echo ""					1>&2
	usage
	;;
    esac
done
shift $((OPTIND-1))

# ---------- ---------- ---------- ---------- ---------- ----------

if [[ -z "${AST_VER}" ]]; then
    if [[ -x ../asterisk/build_tools/make_version ]]; then
	pushd ../asterisk	>/dev/null
	AST_REPO=$(build_tools/make_version .)
	popd			>/dev/null
	if [[ $AST_REPO =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	    AST_VER="$AST_REPO"
	    echo "Using [repo] AST_VER=${AST_VER}"
	else
	    AST_REPO=""
	fi
    fi
fi

if [[ -z "${AST_VER}" && -n "${AST_PKG}" ]]; then
    AST_VER="$AST_PKG"
    echo "Using [package] AST_VER=${AST_VER}"
fi

if [[ -z "${RPT_VER}" ]]; then
    if [[ -f ../app_rpt/apps/app_rpt/app_rpt.h ]]; then
	MAJ=$(grep VERSION_MAJOR ../app_rpt/apps/app_rpt/app_rpt.h)
	MIN=$(grep VERSION_MINOR ../app_rpt/apps/app_rpt/app_rpt.h)
	PAT=$(grep VERSION_PATCH ../app_rpt/apps/app_rpt/app_rpt.h)
	RPT_REPO="${MAJ##* }.${MIN##* }.${PAT##* }"
	if [[ "${RPT_REPO}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
	    RPT_VER="${RPT_REPO}"
	    echo "Using [repo] RPT_VER=${RPT_VER}"
	else
	    RPT_REPO=""
	fi
    fi
fi

if [[ -z "${RPT_VER}" && -n "${RPT_PKG}" ]]; then
    RPT_VER="$RPT_PKG"
    echo "Using [package] RPT_VER=${RPT_VER}"
fi

if [[ -z "${REL_VER}" ]]; then
    if [[ -n "${AST_REPO}" && -n "${RPT_REPO}" ]]; then
	REL_VER=1
	echo "Using REL_VER=$REL_VER"
    elif [[ -n "${REL_PKG}" ]]; then
	REL_VER="$REL_PKG"
	echo "Using [package] REL_VER=$REL_VER"
    fi
fi

if [[ -z "${AST_VER}" || -z "${RPT_VER}" || -z "${REL_VER}" ]]; then
    echo "***"					1>&2
    echo "*** Version(s) not specified"		1>&2
    echo "***"					1>&2
    echo ""					1>&2
    usage
fi

# ---------- ---------- ---------- ---------- ---------- ----------

EPOCH="2"
FULL_REL="${REL_VER}.deb$(lsb_release -rs 2> /dev/null)"
VSTR="${AST_VER}+asl3-${RPT_VER}"

BASE_DIR="$(pwd -P)"
BASE_DIR="${BASE_DIR%/asl3-asterisk}"
ASL3_ASTERISK_DIR="${BASE_DIR}/asl3-asterisk"
ASTERISK_DIR="${BASE_DIR}/asterisk"
APP_RPT_DIR="${BASE_DIR}/app_rpt"

if [[ -n "${MERGE_DIR}" ]]; then
    REAL_MERGE_DIR=$(realpath -m "${MERGE_DIR}")

    REAL_ASTERISK_DIR=$(realpath -m "${ASTERISK_DIR}")
    if [[ "${REAL_MERGE_DIR}" = "${REAL_ASTERISK_DIR}" ]]; then
	echo "MERGE_DIR conflicts with \"asterisk\" source directory"
	exit 1
    fi

    REAL_APP_RPT_DIR=$(realpath -m "${APP_RPT_DIR}")
    if [[ "${REAL_MERGE_DIR}" = "${REAL_APP_RPT_DIR}" ]]; then
	echo "MERGE_DIR conflicts with \"app_rpt\" source directory"
	exit 1
    fi
elif [[ $DO_TEST -ne 0 ]]; then
    MERGE_DIR="/usr/src/asterisk-${AST_VER}-${RPT_VER}"
else
    MERGE_DIR="${BASE_DIR}/asl3-asterisk-${VSTR}"
fi
echo "Merged build directory : ${MERGE_DIR}"

MERGE_EMPTY=0
if [[ ! -d "${MERGE_DIR}" ]]; then
    # directory does not exist
    MERGE_EMPTY=1
else
    find "${MERGE_DIR}" -mindepth 1 -maxdepth 1 ! -name '.PREREQ_INSTALLED' -print -quit >/dev/null
    if [[ $? -ne 0 ]]; then
	# did NOT find any files other than .PREREQ_INSTALLED
	MERGE_EMPTY=1
    fi
fi

if [[ $DO_TEST -ne 0 ]]; then
    TESTSUITE_DIR="$BASE_DIR/testsuite"
    TESTSUITE_MERGE_DIR=$(dirname "${MERGE_DIR}")
    TESTSUITE_MERGE_DIR+="/testsuite"

    REAL_TESTSUITE_DIR=$(realpath -m "${TESTSUITE_DIR}")
    REAL_TESTSUITE_MERGE_DIR=$(realpath -m "${TESTSUITE_MERGE_DIR}")
    if [[ "$REAL_TESTSUITE_MERGE_DIR" = "${REAL_TESTSUITE_DIR}" ]]; then
	echo "TESTSUITE_MERGE_DIR conflicts with \"testsuite\" source directory"
	exit 1
    fi

    echo "Test suite directory   : ${TESTSUITE_MERGE_DIR}"
fi

DO_ZAP=0
DO_SOURCE=0
DO_CLEAN=0
DO_BUILD=0
DO_INSTALL=0
DO_PACKAGE=0

DO_DEBUG=
if [[ $DO_TEST -ne 0 ]]; then
    DO_DEBUG="devmode"
fi

DO_THIN=0

if [[ $# -eq 0 ]]; then
    echo "***"					1>&2
    echo "*** No action(s) specified"		1>&2
    echo "***"					1>&2
    echo ""					1>&2
    usage
fi

while [[ $# -gt 0 ]]; do
    case "${1}" in
    "zap" )
	DO_ZAP=1
	;;
    "source" )
	DO_SOURCE=1
	;;
    "clean" )
	DO_CLEAN=1
	;;
    "build" )
	if [[ $MERGE_EMPTY -ne 0 || $DO_ZAP -gt 0 ]]; then
	    DO_SOURCE=1
	fi
	DO_BUILD=1
	;;
    "install" )
	if [[ $MERGE_EMPTY -ne 0 ]]; then
	    DO_SOURCE=1
	fi
	if [[ $DO_SOURCE -gt 0 ]]; then
	    DO_BUILD=1
	elif [[ ! -x "${MERGE_DIR}/main/asterisk" ]]; then
	    DO_BUILD=1
	fi
	DO_INSTALL=1
	;;
    "package" )
	if [[ $MERGE_EMPTY -ne 0 ]]; then
	    DO_SOURCE=1
	fi
	if [[ $USE_SYMLINKS -ne 0 || -L "${MERGE_DIR}/README.md" ]]; then
	    echo "***"							1>&2
	    echo "*** Can't create packages with symlink'd source"	1>&2
	    echo "***"							1>&2
	    exit 1
	fi
	if [[ $DO_SOURCE -gt 0 ]]; then
	    DO_BUILD=1
	elif [[ ! -x "${MERGE_DIR}/main/asterisk" ]]; then
	    DO_BUILD=1
	fi
	DO_PACKAGE=1
	;;
    "debug" )
	if [[ -n "$DO_DEBUG" ]]; then
	    if [[ $DO_TEST -gt 0 ]]; then
		echo "**"						1>&2
		echo "*** Can't specify both \"debug\" and \"test\""	1>&2
		echo "***"						1>&2
		exit 1
	    elif [[ "$DO_DEBUG" != "debug" ]]; then
		echo "***"						1>&2
		echo "*** Can't specify both \"debug\" and \"devmode\""	1>&2
		echo "***"						1>&2
		exit 1
	    fi
	fi
	DO_DEBUG="debug"
	;;
    "devmode" )
	if [[ -n "$DO_DEBUG" && "$DO_DEBUG" != "devmode" ]]; then
	    echo "***"							1>&2
	    echo "*** Can't specify both \"devmode\" and \"debug\""	1>&2
	    echo "***"							1>&2
	    exit 1
	fi
	DO_DEBUG="devmode"
	;;
    "thin" )
	DO_THIN=1
	;;
    * )
	usage
	;;
    esac
    shift
done

case "${AST_VER}" in
    20.* )
		QUILT_SERIES="debian/patches/series.v20"
		;;
    22.* )
		case "${AST_VER}" in
    		22.[0-5].* )
				QUILT_SERIES="debian/patches/series.v22.0"
				;;
    		* )
				QUILT_SERIES="debian/patches/series.v22.6"
				;;
		esac
		;;
    23.* )
		case "${AST_VER}" in
    		23.0.* )
				QUILT_SERIES="debian/patches/series.v23.0"
				;;
    		23.1.* )
				QUILT_SERIES="debian/patches/series.v23.1"
				;;
    		* )
				QUILT_SERIES="debian/patches/series.v23.2"
				;;
		esac
		;;
    * )
		echo "***"							1>&2
		echo "*** Unsupported Asterisk version"	1>&2
		echo "***"							1>&2
		exit 1
		;;
esac

if [[ -n $DO_DEBUG ]]; then
    BUILD_OPTIONS+=($DO_DEBUG)
fi

if [[ $DO_THIN -ne 0 ]]; then
    BUILD_OPTIONS+=("thin")
fi

if [[ $DO_TEST -ne 0 ]]; then
    BUILD_OPTIONS+=("testsuite")
fi

# ---------- ---------- ---------- ---------- ---------- ----------

create_path()
{
    TARGET=$(realpath -m "$1")
    if [[ -d "${TARGET}" ]]; then
	return
    fi

    PARENT=$(dirname "$TARGET")
    if [[ -w "$PARENT" ]]; then
	mkdir -p "$TARGET"
    else
	${SUDO} mkdir -p "$TARGET"
	${SUDO} chown "$USER": "$TARGET"
    fi
}

# ---------- ---------- ---------- ---------- ---------- ----------

do_zap()
{
    if [[ $MERGE_EMPTY -ne 0 ]]; then
	return
    fi

    echo "The merge directory is \"${MERGE_DIR}\""
    echo ""
    read -p "Do you really want to clean (empty) all content here? (y/[n]): " answer
    case "$answer" in
	[Yy]* )
	    ;;
	* )
	    echo "Not zapping the merge directory"
	    return
	    ;;
    esac

    pushd "${MERGE_DIR}"

    # clean out any prior content
    echo ""
    echo "Cleaning (emptying) merge directory"

    HAVE_PREREQ=0
    if [[ -e ".PREREQ_INSTALLED" ]]; then
	HAVE_PREREQ=1
    fi

    rm -rf [a-zA-Z]* .[a-zA-Z]*

    if [[ $HAVE_PREREQ -ne 0 ]]; then
	touch ".PREREQ_INSTALLED"
    fi

    popd
}

# ---------- ---------- ---------- ---------- ---------- ----------

copy_path()
{
    src_path="$1"
    dst_path="$2"

    if [[ ! -e "${src_path}" ]]; then
	echo "info: not copying: $src_path"
	return
    fi

    if [[ $USE_SYMLINKS -ne 0 ]]; then
	link_path "${src_path}" "${dst_path}"
	return
    fi

    if [[ -f "$src_path" ]]; then
	echo "Copy \"$src_path/$path\" --> \"$dst_path/$path\""
	cp -p "${src_path}" "${dst_path}"
    else
	( cd "$src_path" ; find . -path ".git" -prune -o -print )	\
	| while read -r path; do
	    path="${path#./}"
	    if [[ -d "$src_path/$path" ]]; then
		if [[ ! -d "$dst_path/$path" ]]; then
		    echo "Copy \"$src_path/$path\" --> \"$dst_path/$path\""
		    mkdir -p "$dst_path/$path"
		    tar --create --directory="${src_path}" --file=- .	\
		    | tar --extract --directory="${dst_path}" --file=-
		fi
	    elif [[ -f "$src_path/$path" ]]; then
		if [[ -f "$dst_path/$path" ]]; then
		    if [[ $USE_COMPARE -ne 0 ]]; then
			cmp --silent "$src_path/$path" "$dst_path/$path"
			if [[ $? -ne 0 ]]; then
			    echo "Update \"$src_path/$path\" --> \"$dst_path/$path\""
			    cp -p "$src_path/$path" "$dst_path/$path"
			fi
		    else
			if [[ "$(stat -c %Y "$src_path/$path")" -gt "$(stat -c %Y "$dst_path/$path")" ]]; then
			    echo "Update \"$src_path/$path\" --> \"$dst_path/$path\""
			    cp -p "$src_path/$path" "$dst_path/$path"
			fi
		    fi
		else
		    echo "Add \"$src_path/$path\" --> \"$dst_path/$path\""
		    cp -p "$src_path/$path" "$dst_path/$path"
		fi
	    else
		echo "???? \"$src_path/$path\""
		ls -ld $src_path/$path
	    fi
        done

    fi
}

link_path()
{
    src_path="$1"
    dst_path="$2"

    echo "Link \"${src_path}\" to \"${dst_path}\""

    if [[ -f "$src_path" ]]; then
	path=$(basename $src_path)
	rel_dir=$(realpath --relative-to="$(dirname "$dst_path")" "$(dirname $src_path)")
	if [[ ! -e "$dst_path" || -L "$dst_path" ]]; then
	    ln -f -s "$rel_dir/$path" "$dst_path"
	else
	    echo "  Not replacing \"$dst_path\""
	fi
    else
	mkdir -p "${dst_path}"
	( cd "$src_path" ; find . -mindepth 1 -path ".git" -prune -o -print )	\
	| while read -r path; do
	    path="${path#./}"
	    rel_dir=$(realpath --relative-to="$(dirname "$dst_path/$path")" "$src_path")
	    if [[ -d "$src_path/$path" ]]; then
		mkdir -p "$dst_path/$path"
	    else
		if [[ ! -e "$dst_path/$path" || -L "$dst_path/$path" ]]; then
		    ln -f -s "$rel_dir/$path" "$dst_path/$path"
		else
		    echo "  Not replacing \"$dst_path/$path\""
		fi
	    fi
        done
    fi
}

# ---------- ---------- ---------- ---------- ---------- ----------

prepare_patched_files()
{
    patch="$1"

    echo "info: preparing to apply patch: $patch"
    for file in $(grep -E '^--- |^\+\+\+ ' $patch | cut -d' ' -f2 | sed 's|^a/||;s|^b/||' | sort -u); do
	if [[ -L "$file" ]]; then
	    echo "  replacing symlink'd file: $file"
	    cp -p $file $file-ORIG
	    mv $file-ORIG $file
	fi
    done
}

apply_patch()
{
    patch="$1"

    if [[ ! -f "${patch}" ]]; then
	echo "info: skipping patch: $patch"
	return
    fi

    if [[ $USE_SYMLINKS -ne 0 ]]; then
	prepare_patched_files "${patch}"
    fi
    echo "info: applying patch: $patch"
    patch -p1 < "${patch}"
}

prepare_patch_series()
{
    for patch in $(cat ${QUILT_SERIES}); do
	if [[ $patch =~ ^# ]]; then 
	    continue
	fi
	prepare_patched_files "debian/patches/$patch"
    done
}

revert_patch()
{
    patch="$1"

    if [[ ! -r "${patch}" ]]; then
	#echo "info: not reverting patch: $patch"
	return
    fi

    # check that all of the files being updated are regular files (and not symlinks)
    for file in $(grep -E '^--- |^\+\+\+ ' $patch | cut -d' ' -f2 | sed 's|^a/||;s|^b/||' | sort -u); do
	if [[ ! -f $file || -L $file ]]; then
	    echo "not reverting patch: $patch (expecting file: $file)"
	    return
	fi
    done

    echo "info: unapplying patch: $patch"
    patch -p1 -R < "${patch}"
}

# ---------- ---------- ---------- ---------- ---------- ----------

add_asterisk()
{
    if [[ ! -d "${ASTERISK_DIR}" ]]; then
	echo "Cloning \"asterisk\", tag==${AST_VER}"
	git clone https://github.com/asterisk/asterisk.git "${ASTERISK_DIR}"
	( cd "${ASTERISK_DIR}"; git checkout ${AST_VER} )
    fi
}

add_app_rpt()
{
    if [[ ! -d "${APP_RPT_DIR}" ]]; then
	echo "Cloning \"app_rpt\", tag==${RPT_VER}"
	git clone https://github.com/AllStarLink/app_rpt.git "${APP_RPT_DIR}"
	( cd "${APP_RPT_DIR}"; git checkout ${RPT_VER} )
    fi
}

add_asl3-asterisk()
{
    if [[ ! -d "${ASL3_ASTERISK_DIR}" ]]; then
	echo "Cloning \"asl3-asterisk\""
	git clone https://github.com/AllStarLink/asl3-asterisk.git "${ASL3_ASTERISK_DIR}"
    fi
}

add_testsuite()
{
    if [[ ! -d "${TESTSUITE_DIR}" ]]; then
	echo "Cloning Asterisk \"testsuite\""
	git clone https://github.com/asterisk/testsuite.git "${TESTSUITE_DIR}"
	if [[ -n "${TESTSUITE_VER}" ]]; then
	    ( cd "${TESTSUITE_DIR}"; git checkout ${TESTSUITE_VER} )
	fi
    fi
}

merge_asterisk()
{
    if [[ -f "${MERGE_DIR}/.BEFORE-BUILD-APPLIED" ]]; then
	# Revert "asterisk" patches
	pushd "${MERGE_DIR}"
	dpkg-source --after-build .
	rm -f .BEFORE-BUILD-APPLIED
	popd
    fi

    copy_path "${ASTERISK_DIR}"		"${MERGE_DIR}"
}

merge_app_rpt()
{
    if [[ $MERGE_EMPTY -eq 0 ]]; then
	pushd "${MERGE_DIR}"
	if [[ -r Makefiles.diff ]]; then
	    # if app_rpt <= 3.2.x, Asterisk <= 20.x.x
	    revert_patch Makefiles.diff
	else
	    # if app_rpt >= 3.3.x, Asterisk > 20.x.x
	    revert_patch apps/Makefile.diff
	    revert_patch channels/Makefile.diff
	fi
	revert_patch res/Makefile.diff
	revert_patch utils/Makefile.diff
	popd
    fi

    pushd "${APP_RPT_DIR}"
    if [[ -f Makefiles.diff ]]; then
	# if Asterisk 20 (and we have already pulled the [old] Makefiles.diff)
	copy_path "Makefiles.diff"	"${MERGE_DIR}/Makefiles.diff"
    elif [[ "${AST_VER}" =~ 20.* && ! -f "${MERGE_DIR}/Makefiles.diff" ]]; then
	# if Asterisk 20.x.x with a newer app_rpt
	(cd "${MERGE_DIR}"; wget https://github.com/AllStarLink/app_rpt/raw/refs/heads/3.2.0/Makefiles.diff )
    fi
    copy_path "apps"			"${MERGE_DIR}/apps"
    copy_path "channels"		"${MERGE_DIR}/channels"
    copy_path "configs/rpt"		"${MERGE_DIR}/configs/asl3"
    copy_path "include"			"${MERGE_DIR}/include"
    copy_path "res"			"${MERGE_DIR}/res"
    copy_path "utils"			"${MERGE_DIR}/utils"
    popd

    pushd "${MERGE_DIR}"
    if [[ -f Makefiles.diff ]]; then
	# if app_rpt <= 3.2.x, Asterisk <= 20.x.x
	apply_patch Makefiles.diff
    else
	# if app_rpt >= 3.3.x, Asterisk > 20.x.x
	apply_patch apps/Makefile.diff
	apply_patch channels/Makefile.diff
    fi
    apply_patch res/Makefile.diff
    apply_patch utils/Makefile.diff
    popd
}

merge_testsuite()
{
    copy_path "${TESTSUITE_DIR}"	"${TESTSUITE_MERGE_DIR}"
}

merge_app_rpt_tests()
{
    if [[ -d "${TESTSUITE_MERGE_DIR}" ]]; then
	pushd "${TESTSUITE_MERGE_DIR}"
	revert_patch tests/apps/tests_apps.diff
	popd
    fi

    pushd "${APP_RPT_DIR}"
    copy_path "tests/apps/tests_apps.diff"	"${TESTSUITE_MERGE_DIR}/tests/apps/tests_apps.diff"
    copy_path "tests/apps/rpt"			"${TESTSUITE_MERGE_DIR}/tests/apps/rpt"
    popd

    pushd "${TESTSUITE_MERGE_DIR}"
    apply_patch tests/apps/tests_apps.diff
    popd
}

merge_asl3_asterisk()
{
    # ensure that the debian/patches/series file is a fresh copy/link
    rm -f "${MERGE_DIR}/debian/patches/series"

    pushd "${ASL3_ASTERISK_DIR}"
    copy_path "debian"			"${MERGE_DIR}/debian"
    copy_path "rpt-sounds"		"${MERGE_DIR}/rpt-sounds"
    copy_path "etc"			"${MERGE_DIR}/etc"
    popd
}

prepare_build_directory()
{
    #
    # Create the merged build directory
    #
    create_path "${MERGE_DIR}"

    if [[ ! -f "${MERGE_DIR}/.PREREQ_INSTALLED" ]]; then
	#
	# Make sure we have all of the build dependencies
	#
	echo "Installing build dependencies"
	${SUDO} "${ASL3_ASTERISK_DIR}/install-build-deps"
	touch "${MERGE_DIR}/.PREREQ_INSTALLED"

	#
	# Create the merged build directory
	#
	echo "Creating merged source directory (${MERGE_DIR})"
    else
	#
	# Re-create the merged build directory
	# (note: the build dependencies have already been installed)
	#
	echo "Re-creating merged source directory (${MERGE_DIR})"
    fi

    echo "Add \"asterisk\""
    merge_asterisk

    echo "Add \"app_rpt\" modules, apply patches"
    merge_app_rpt

    echo "Add \"debian\", \"rpt-sounds\""
    merge_asl3_asterisk

    pushd "${MERGE_DIR}"

    if [[ "$QUILT_SERIES" != "debian/patches/series" ]]; then
	echo "Select patch series ($QUILT_SERIES)"
	DPKG_VENDOR=$(dpkg-vendor --query vendor | tr '[:upper:]' '[:lower:]')
	DPKG_SERIES=$(basename $QUILT_SERIES)
	VENDOR_SERIES=debian/patches/${DPKG_VENDOR}.series
	rm -f ${VENDOR_SERIES}
	ln -s ${DPKG_SERIES} ${VENDOR_SERIES}
    fi

    echo "Add version"
    rm -rf .version
    echo "${VSTR}" > .version
    if [[ -d ChangeLogs ]]; then
	( cd ChangeLogs && ln -f -s ChangeLog-${AST_VER}.md ChangeLog-${VSTR}.md5 )
    fi
    rm debian/changelog
    debchange				\
	--create			\
	--package asl3-asterisk 	\
	-v ${EPOCH}:${VSTR}-${FULL_REL}	\
	--				\
	"see https://github.com/AllStarLink/app_rpt"
    debchange				\
	--release			\
	""

    if [[ $USE_SYMLINKS -ne 0 ]]; then
	echo "Prepare to-be-patched files (from $QUILT_SERIES)"
	prepare_patch_series
    fi

    echo "Prepare source for building, apply patches (from $QUILT_SERIES)"
    dpkg-source --before-build .
    touch .BEFORE-BUILD-APPLIED

    popd
}

prepare_testsuite_directory()
{
    #
    # Create the Asterisk "testsuite" directory
    #
    create_path "${TESTSUITE_MERGE_DIR}"

    echo "Add Asterisk \"testsuite\""
    merge_testsuite

    echo "Add \"app_rpt\" tests, apply patches"
    merge_app_rpt_tests

    pushd ${TESTSUITE_MERGE_DIR}
    if [[ ! -f ".PREREQ_INSTALLED" ]]; then
	echo "Installing \"testsuite\" pre-requisites"
	${SUDO} apt -y install aptitude
	${SUDO} ./contrib/scripts/install_prereq install
	RC=$?
	if [[ $RC -ne 0 ]]; then
	    echo "install_prereq install failed (exit code $RC)"	1>&2
	    exit 1
	fi

	echo "Setting up \"testsuite\" environment"
	${SUDO} ./setupVenv.sh
	RC=$?
	if [[ $RC -ne 0 ]]; then
	    echo "setupVenv failed (exit code $RC)"			1>&2
	    exit 1
	fi
	touch ".PREREQ_INSTALLED"
    fi
    popd
}

check_executable()
{
    #
    # The Asterisk "testsuite" makes use of the "/tmp" directory. The
    # suite needs to execute files (scripts) and uses more space than
    # what we typically allocate on our appliance devices. Here, we
    # check the "exec/noexec" status of the filesystem.
    #

    local FS=$1
    if findmnt -n -o OPTIONS "$FS" | grep -q -w noexec; then
	return 1
    fi

    return 0
}

check_multiarch()
{
    #
    # Installing packages with "aptitude" can be problematic if any
    # "foreign" [dpkg] architectures are defined. Here, we check for
    # this case and, if possible, we block any unwanted usage.
    #

    OTHER_ARCHS=$(dpkg --print-foreign-architectures)
    if [[ -n "$OTHER_ARCHS" ]]; then
	echo "Multiarch support is enabled on this system."
	echo "  dpkg arch  : $(dpkg --print-architecture)"
	echo "  dpkg multi : $OTHER_ARCHS"
	echo ""

	HOLD=0
	for ARCH in $OTHER_ARCHS; do
	    if dpkg -l | grep -q -E "^ii\s+.+:$ARCH\s"; then
		HOLD=$((HOLD + 1))
	    fi
	done

	if [[ $HOLD -ne 0 ]]; then
	    echo "Multi-arch packages are installed."
	    echo ""
	    return 1
	fi

	for ARCH in $OTHER_ARCHS; do
	    echo "Removing [unused] multiarch support : $ARCH"
	    ${SUDO} dpkg --remove-architecture $ARCH
	done
	echo ""

	${SUDO} apt update
    fi

    return 0
}

preflight_testsuite()
{
    RC=0
    check_executable /tmp || RC=$?
    if [[ $RC -ne 0 ]]; then
	echo "***"								1>&2
	echo "*** The \"testsuite\" needs to exec scripts in \"/tmp\" and"	1>&2
	echo "*** additional space is needed.  To resolve, you can comment"	1>&2
	echo "*** out the \"/etc/fstab\" mount entry (and reboot)."		1>&2
	echo "***"								1>&2
	exit 1
    fi

    RC=0
    check_multiarch || RC=$?
    if [[ $RC -ne 0 ]]; then
	echo "***"								1>&2
	echo "*** Can't install the \"testsuite\" pre-requisite packages"	1>&2
	echo "***"								1>&2
	exit 1
    fi
}

do_source()
{
    # Make sure that we have a copy of the "asterisk" repo
    add_asterisk

    # Make sure that we have a copy of the "app_rpt" repo
    add_app_rpt

    # Make sure that we have a copy of the "asl3-asterisk" repo
    add_asl3-asterisk

    # If testing, make sure that we have a copy of the Asterisk "testsuite" repo
    if [[ $DO_TEST -ne 0 ]]; then
	add_testsuite
    fi

    # Create our merged build directory
    prepare_build_directory

    # If testing, prepare for exec'ing the test suite
    if [[ $DO_TEST -ne 0 ]]; then
	prepare_testsuite_directory
    fi
}

# ---------- ---------- ---------- ---------- ---------- ----------

do_clean()
{
    pushd "${MERGE_DIR}"

    echo "Clean (after building/packaging)"
    dh clean
    RC=$?
    if [[ $RC -ne 0 ]]; then
	echo "dh clean failed (exit code $RC)."		1>&2
	exit 1
    fi

    popd
}

# ---------- ---------- ---------- ---------- ---------- ----------

do_build()
{
    pushd "${MERGE_DIR}"

    echo "Build"
    DEB_BUILD_OPTIONS=${BUILD_OPTIONS[*]}	\
	dh build -j$(nproc --all)
    RC=$?
    if [[ $RC -ne 0 ]]; then
	echo "dh build failed (exit code $RC)."		1>&2
	exit 1
    fi

    popd
}

# ---------- ---------- ---------- ---------- ---------- ----------

do_install()
{
    pushd "${MERGE_DIR}"

    echo "Installing (locally)"
    ${SUDO} make install DESTDIR="${DESTDIR}"
    RC=$?
    if [[ $RC -ne 0 ]]; then
	echo "make install failed (exit code $RC)."	1>&2
	exit 1
    fi

    popd
}

# ---------- ---------- ---------- ---------- ---------- ----------

do_package()
{
    pushd "${MERGE_DIR}"

    echo "Create the [debian] package"
    fakeroot dh binary -j$(nproc --all)
    RC=$?
    if [[ $RC -ne 0 ]]; then
	echo "dh binary failed (exit code $RC)."	1>&2
	exit 1
    fi

    popd
}

# ---------- ---------- ---------- ---------- ---------- ----------

echo ""

if [[ $DO_TEST -ne 0 ]]; then
    preflight_testsuite
fi

if [[ $DO_ZAP -gt 0 ]]; then
    do_zap
fi

if [[ $DO_SOURCE -gt 0 ]]; then
    do_source
fi

if [[ $DO_CLEAN -gt 0 ]]; then
    if [[ $MERGE_EMPTY -eq 0 ]]; then
        do_clean
    fi
fi

if [[ $DO_BUILD -gt 0 ]]; then
    do_build
fi

if [[ $DO_INSTALL -gt 0 ]]; then
    do_install
fi

if [[ $DO_PACKAGE -gt 0 ]]; then
    do_package
fi

