#!/bin/bash

PATH=/usr/bin:/bin:/usr/sbin:/sbin

usage() {
	echo "Usage: $0 -v RELEASE_VERSION" 1>&2; 
	echo ""
	echo "For -v, copy/paste the release name from asl3-asterisk repo."
	echo "Example:"
	echo " install-asl3-beta -v 20.5.0+asl3-0.0.2.fadead4-3"
	exit 1; 
}

while getopts "v:" o; do
    case "${o}" in
        v)
            RPT_VER=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${RPT_VER}" ]; then
    usage
fi

case `uname -m` in
	aarch64)
		ARCH=arm64
		;;
	armv7l)
		ARCH=armhf
		;;
	*)
		ARCH=amd64
		;;
esac

TARF=`echo ${RPT_VER} | sed -e 's/~deb12/.deb12/g'`
if [ ! -f asl3-asterisk-${TARF}-${ARCH}.tar.gz ]; then
	echo "Download asl3-asterisk-${TARF}-${ARCH}.tar.gz to the same directory"
	echo "where this file is located."
	exit 1
fi

apt -y update
apt -y install adduser libc6 libcap2 libcrypt1 libedit2 libjansson4 libpopt0 libsqlite3-0 \
	libssl3 libsystemd0 liburiparser1 libuuid1 libxml2 libxslt1.1 \
	libasound2 libbluetooth3 libc-client2007e libcodec2-1.0 libcurl4 libglib2.0-0 libgmime-3.0-0 \
	libgsm1 libical3 libiksemel3 libjack-jackd2-0 libldap-2.5-0 liblua5.1-0 libmariadb3 libneon27 \
	libodbc2 libogg0 libopenr2-3 libportaudio2 libpq5 libpri1.4 libradcli4 libresample1 \
	libsnmp40 libspandsp2 libspeex1 libspeexdsp1 libsqlite3-0 libsrtp2-1 libss7-2.0 libssl3 \
	libsybdb5 libtonezone2.0 libunbound8 libusb-0.1-4 libvorbis0a libvorbisenc2 libvorbisfile3 \
	libxml2 zlib1g \
	dkms make libc6-dev dpkg-dev gcc gawk \
	procps fxload \
	debhelper module-assistant \
	debhelper perl \
	linux-headers-`uname -r`

tar xvfz asl3-asterisk-${TARF}-${ARCH}.tar.gz

PKG_LIST="asl3-asterisk_${RPT_VER}_${ARCH}.deb asl3-asterisk-config_${RPT_VER}_all.deb asl3-asterisk-dev_${RPT_VER}_all.deb asl3-asterisk-doc_${RPT_VER}_all.deb asl3-asterisk-modules_${RPT_VER}_${ARCH}.deb dahdi-dkms_3.2.0+asl-8_all.deb dahdi-linux_3.2.0+asl-8_all.deb dahdi-source_3.2.0+asl-8_all.deb"

for d in ${PKG_LIST}
do
	if [ ! -f $d ]; then
		echo "Missing file: $d"
		exit 1
	fi
done

echo "!!!!"
echo "!!!! About to install the following packages:"
echo ""
echo $PKG_LIST
echo ""
echo "!!!! Be observant for any errors"
echo "!!!!"

dpkg -i $PKG_LIST
rm $PKG_LIST

if ! `lsmod | grep -q dahdi`; then
	echo "Error: dahdi module not loaded. Were there dpkg errors?"
	exit 1
fi

exit 0


