#! /bin/sh

require_module()
{
    module="$1"
    module_re=$(printf '%s' "$module" | sed 's/\./\\./g')
    re1="^[[:blank:]]*(load|noload|require)[[:blank:]]*=[[:blank:]]*${module_re}([[:blank:]]*(;.*)?)?[[:blank:]]*$"
    re2="^[[:blank:]]*(load|require)[[:blank:]]*=[[:blank:]]*${module_re}([[:blank:]]*(;.*)?)?[[:blank:]]*$"

    grep -E "$re1" /etc/asterisk/modules.conf | tail -n 1 | grep -E -q "$re2"
    if [ $? -ne 0 ]; then
	printf 'require = %s\n' "$module" >> /etc/asterisk/modules.conf
    fi
}

update_asl_configuration()
{
    # Update "modules.conf" to use non-DAHDI bridging
    perl -0 -pi -e '
	s{
	    (^load[[:blank:]]*=[[:blank:]]*app_transfer\.so(?:[[:blank:]][^\n]*)?\n)
	    ^[[:blank:]]*\n
	    ^;[[:blank:]]*Channel[[:blank:]]+Drivers\n
	    ^[[:blank:]]*\n
	}{
	    $1 .
	    "\n" .
	    "; Bridging\n" .
	    "\n" .
	    "require = bridge_softmix.so              ; Multi-party software based channel mixing\n" .
	    "\n" .
	    "; Channel Drivers\n" .
	    "\n"
	}gmxe;
	s{
	    ^;[[:blank:]]*Channel[[:blank:]]+Drivers\n
	    ^[[:blank:]]*\n
	    ^(load|noload|require)[[:blank:]]*=[[:blank:]]*chan_dahdi\.so(?:[[:blank:]][^\n]*)?\n
	}{
	    "; Channel Drivers\n" .
	    "\n" .
	    "require = chan_bridge_media.so           ; Bridge Media Channel Driver\n" .
	    "noload  = chan_dahdi.so                  ; DAHDI Telephony w/PRI & SS7 & MFC/R2\n"
	}gmxe;
	s{
	    ^(load|noload|require)[[:blank:]]*=[[:blank:]]*chan_dahdi\.so(?:[[:blank:]][^\n]*)?\n
	}{
	    "noload  = chan_dahdi.so                  ; DAHDI Telephony w/PRI & SS7 & MFC/R2\n"
	}gmxe;
	s{
	    ^(load|noload|require)[[:blank:]]*=[[:blank:]]*res_timing_dahdi\.so(?:[[:blank:]][^\n]*)?\n
	}{
	    "noload  = res_timing_dahdi.so            ; DAHDI Timing Interface\n"
	}gmxe;
	s{
	    ^;load[[:blank:]]*=[[:blank:]]*bridge_softmix\.so(?:[[:blank:]][^\n]*)?\n
	}{}gmx;
	s{
	    ^;load[[:blank:]]*=[[:blank:]]*chan_bridge_media\.so(?:[[:blank:]][^\n]*)?\n
	}{}gmx;
    ' /etc/asterisk/modules.conf

    require_module "bridge_softmix.so"
    require_module "chan_bridge_media.so"

    # Update "rpt.conf" to use non-DAHDI bridging
    perl -pi -e '
	s;dahdi/pseudo;Local/pseudo;g
    ' /etc/asterisk/rpt.conf

    # Update "extensions.conf" to use non-DAHDI bridging
    perl -0 -pi -e '
	s{
	    ^\[pstn-out\]\n
	    ^exten[[:blank:]]*=>[[:blank:]]*_NXXNXXXXXX,1,playback\(ss-noservice\)\n
	    ^[[:blank:]]+same[[:blank:]]*=>[[:blank:]]*n,Congestion\n
	    ^[[:blank:]]*\n
	}{
	    "[pstn-out]\n" .
	    "exten => _NXXNXXXXXX,1,Wait(1)\n" .
	    "	same => n,Playback(ss-noservice)\n" .
	    "	same => n,Hangup\n" .
	    "\n"
	}gmsxe;
	s{
	    ^;\[pstn-out\]\n
	    ;exten[[:blank:]]*=>[[:blank:]]*_NXXNXXXXXX,1,Dial\(IAX2/allstar-autopatch/\\\$\{EXTEN\}\)\n
	    ;[[:blank:]]+same[[:blank:]]*=>[[:blank:]]*n,Busy\n
	    [[:blank:]]*\n
	}{
	    ";[pstn-out]\n" .
	    ";exten => _NXXNXXXXXX,1,Wait(1)\n" .
	    ";	same => n, Dial(IAX2/allstar-autopatch/\${EXTEN})\n" .
	    ";	same => n,Busy\n" .
	    "\n"
	}gmxe;
    ' /etc/asterisk/extensions.conf
}

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>

case "$1" in
    configure)
	set +e # ignore errors temporarily

	# find conffiles under /etc/asterisk belonging to asterisk-config
	# and chown them to user asterisk.
	dpkg-query -W -f='${Conffiles}\n' asl3-asterisk-config 2>/dev/null | \
	  sed -nr -e 's; (/etc/asterisk/.*) [0-9a-f]*;\1;p' | \
	while read conffile; do
		chown asterisk: ${conffile} 2>/dev/null
	done

	# handle them in the end with a glob since it's way faster
	dpkg-statoverride --quiet --list '/etc/asterisk/*' | while read STAT; do
		chown `echo $STAT | cut -d' ' -f 1,2,4 | sed 's/ /:/'` \
			2>/dev/null
	done

	# make sure that custom sounds are enabled
	# https://github.com/AllStarLink/asl3-asterisk/issues/34
	perl -pi -e 's/^;sounds_search_custom_dir\s+=\s+no/sounds_search_custom_dir = yes/g' \
		/etc/asterisk/asterisk.conf

	# update the asterisk module directory path
	perl -pi -e "s;/usr/lib/.*-linux-gnu/asterisk/modules;/usr/lib/`arch`-linux-gnu/asterisk/modules;" \
		/etc/asterisk/asterisk.conf

	# change insecure default passwords, if present
	RAND_IAX=$(openssl rand -hex 16)
	perl -pi -e "s/Your_Secret_Password_Here/${RAND_IAX}/g" \
		/etc/asterisk/iax.conf
	perl -pi -e "s/Your_Secret_Pasword_Here/${RAND_IAX}/g" \
		/etc/asterisk/iax.conf

	# update the configuration files to use asterisk (non-DAHDI) bridging
	pkg_ver="$(dpkg-query -W -f='${Version}\n' asl3-asterisk 2>/dev/null || echo "")"
	asl_ver="$(printf '%s\n' "$pkg_ver" | sed -n 's/.*+asl3-\([^-]*\)-.*/\1/p')"
	if [ -n "$asl_ver" ] && dpkg --compare-versions "$asl_ver" ge "3.8.0"; then
		update_asl_configuration
	fi

	set -e
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# dh_installdeb will replace this with shell code automatically
# generated by other debhelper scripts.

#DEBHELPER#

exit 0


