name: make_and_publish_pkgs
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for ${{ inputs.os }}/${{ inputs.arch }}, Publish to ${{ inputs.deployment-environment }}
on: 
  workflow_dispatch:
    inputs:
      ast-ver:
        description: 'Asterisk LTS Version Base'
        type: string
        default: '20.7.0'
        required: true
      rpt-ver:
        description: 'app_rpt Version Tag'
        type: string
        required: true
      asl3-ver:
        description: 'Package Revision (usually 1)'
        type: string
        required: true
      arch:
        description: 'Platform Architecture'
        type: choice
        options:
        - amd64
        - arm64
      os:
        description: 'Debian Release Version'
        type: choice
        options:
          - bookworm
          - bullseye
      gh-rel:
        description: 'GitHub Release Tag (for debs)'
        type: string
      deployment-environment:
        description: 'Aptly Repository Stream'
        type: choice
        options:
        - development
        - testing
        - production
      commit-versioning:
        description: 'Commit Versioning'
        type: choice
        options:
          - default
          - yes
          - no

jobs:
  make-packages:
    uses: AllStarLink/asl3-asterisk/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: ./builder/dockerbuild.sh -a ${{ inputs.arch  }} -o ${{ inputs.os }} --ast-ver ${{ inputs.ast-ver }} --rpt-ver ${{ inputs.rpt-ver }} --asl3-ver ${{ inputs.asl3-ver}} --gh-rel ${{ inputs.gh-rel }} ${{ (inputs.commit-versioning == 'yes' || (inputs.commit-versioning == 'default' && inputs.deployment-environment == 'development')) && '-r' || null }}
      arch: ${{ inputs.arch == 'armhf' && 'arm64' || inputs.arch == 'aarch64' && 'arm64' || inputs.arch == 'amd64' && 'x86_64' || inputs.arch == 'riscv64' && 'x86_64' || inputs.arch }}
      artifact-path: '_debs/*'
    secrets: inherit
#  publish-packages:
#    uses: AllStarLink/asl3-asterisk/.github/workflows/publish_artifacts_to_aptly.yml@develop
#    with:
#      repo-name: asl_builds-${{inputs.os}}${{ inputs.deployment-environment == 'production' && '' || inputs.deployment-environment == 'testing' && '-testing' || inputs.deployment-environment == 'development' && '-devel' || null }}
#    secrets: inherit
#    needs: make-packages
