name: "Make and Publish Pkgs"
run-name: Package ${{ github.event.repository.name }}(${{ github.ref_name }}) for ${{ inputs.os }}/${{ inputs.arch }}, Publish to ${{ inputs.deployment-environment }}
on: 
  workflow_dispatch:
    inputs:
      ast-ver:
        description: 'Asterisk LTS Version Base'
        type: string
        default: '20.8.1'
        required: true
      rpt-ver:
        description: 'app_rpt Version Tag'
        type: string
        default: '3.0.'
        required: true
      package-ver:
        description: 'Package Revision (usually 1)'
        type: string
        default: '1'
        required: true
      arch:
        description: 'Platform Architecture'
        type: choice
        options:
        - amd64
        - arm64
      os:
        description: 'Debian Release Version'
        type: choice
        options:
          - bookworm
          - bullseye
      gh-rel:
        description: 'GitHub Release Tag (for debs)'
        type: string
      aptly-repo:
        description: 'Aptly Repository Stream'
        type: choice
        options:
          - devel
          - beta

env:
  APTLY_API_USER: ${{secrets.APTLY_API_USER}}
  APTLY_API_PASS: ${{secrets.APTLY_API_PASS}}
  APTLY_GPG_PASSPHRASE: ${{secrets.APTLY_GPG_PASSPHRASE}}


jobs:
  make-packages:
    uses: AllStarLink/asl3-workflows/.github/workflows/ephemeral_ec2_run-this.yml@develop
    with:
      run-this: ./builder/dockerbuild.sh -a ${{ inputs.arch  }} -o ${{ inputs.os }} --ast-ver ${{ inputs.ast-ver }} --rpt-ver ${{ inputs.rpt-ver }} --package-ver ${{ inputs.package-ver}} --gh-rel ${{ inputs.gh-rel }} ${{ (inputs.commit-versioning == 'yes' || (inputs.commit-versioning == 'default' && inputs.deployment-environment == 'development')) && '-r' || null }} --repo ${{ inputs.aptly-repo }}
      arch: ${{ inputs.arch == 'armhf' && 'arm64' || inputs.arch == 'aarch64' && 'arm64' || inputs.arch == 'amd64' && 'x86_64' || inputs.arch == 'riscv64' && 'x86_64' || inputs.arch }}
      artifact-path: '/actions-runner/_work/asl3-asterisk/_debs/'
    secrets: inherit
