name: publish_artifacts_to_ssh
on: 
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: ''
      repo-name:
        required: true
        type: string
jobs:
  process-artifacts:
    runs-on: [self-hosted, lightsail]
    name: Process all artifacts
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{inputs.artifact-name}}
          path: ${{runner.temp}}/artifacts
      - name: Display structure of downloaded files
        run: ls -R $RUNNER_TEMP
